### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by somedevreally** [derat/nitter-rss-proxy#1]
Hi,

thanks for this, it would be great if you can support docker image.

thanks

**Comment by derat** [comment]
I don't really know what I'm doing, but let me know if the Dockerfile that I just committed works for you.

**Comment by somedevreally** [comment]
awesome, i got it working. so am accessing it with
`http://localhost:8080/nasa` i get the rss
do i have to do anything when rate limit hits? or will it auto change to another instance?

thanks

**Comment by derat** [comment]
Glad that it works!

I'd recommend choosing multiple public instances from the list at https://github.com/zedeus/nitter/wiki/Instances. You can verify that each one is working by running a command like this:

```sh
nitter-rss-proxy -user nasa -instances https://nitter.it/
```

(or whatever equivalent is needed to pass those `-user` and `-instance` flags to your Docker image).

Then pass the instances that you chose as a comma-separated list when you run the proxy, e.g.

```sh
nitter-rss-proxy -instances https://nitter.it/,https://nitter.ca/,...
```

The proxy will cycle through the instances as it handles requests, and if an instance times out or reports an error, it'll automatically move on to the next one in the list.

**Comment by somedevreally** [comment]
i dont think i can pass -user or -instance in docker-compose. not as enviroment :(
can it be implemented in `main.go` getting list from `https://github.com/zedeus/nitter/wiki/Instances`
just a suggestion.

thanks

**Comment by derat** [comment]
I don't know anything about docker-compose, but do any of the answers at https://stackoverflow.com/questions/37366857/how-to-pass-arguments-to-entrypoint-in-docker-compose-yml help?

I'd rather not make the program automatically get a list of instances for a variety of reasons (it'd add a network dependency on GitHub, the proxy would need to parse that webpage, some instances are flaky or buggy and there would probably still need to be a way to manually exclude them, etc.).

**Comment by somedevreally** [comment]
here is my docker-compose.yml
```
nitterproxy:
    container_name: nitterproxy
    image: nitterproxy
    ports:
      - 8080
    restart: always
    build:
      context: ./nitterproxy
    command: [nitterproxy -instances https://nitter.it/,https://nitter.ca/]
```
how do i test it now? 
if i go to image console and run `nitterproxy -instances https://nitter.it/,https://nitter.ca/`
i get this error
`sh: nitterproxy: not found`

**Comment by derat** [comment]
The `Dockerfile` that I committed installs the executable at `/nitter-rss-proxy`. Does changing the final line of your `docker-compose.yml` to something like this work?

```yaml
  command: [ '/nitter-rss-proxy', '-addr', '0.0.0.0:8080', '-instances', 'https://nitter.it,https://nitter.ca' ]
```

**Comment by somedevreally** [comment]
ok i changed last line and when i runthe command on console ` '/nitter-rss-proxy', '-addr', '0.0.0.0:8080', '-instances', 'https://nitter.it,https://nitter.ca' ` it still says not found.

**Comment by derat** [comment]
It seems weird to me that running `/nitter-rss-proxy` on the console wouldn't work, but this is beyond my knowledge. The Dockerfile seems pretty trivial and works on Google Cloud Run, so hopefully someone with more knowledge about docker-compose would be able to tell you what needs to be changed in your `docker-compose.yml` file.

**Comment by zydou** [comment]
> here is my docker-compose.yml
> 
> ```
> nitterproxy:
>     container_name: nitterproxy
>     image: nitterproxy
>     ports:
>       - 8080
>     restart: always
>     build:
>       context: ./nitterproxy
>     command: [nitterproxy -instances https://nitter.it/,https://nitter.ca/]
> ```
> 
> how do i test it now? if i go to image console and run `nitterproxy -instances https://nitter.it/,https://nitter.ca/` i get this error `sh: nitterproxy: not found`

Because the `Dockerfile` has an `ENTRYPOINT` entry, the `command: ...` line in your `docker-compose.yml` is appended after the `ENTRYPOINT` line. ([more info](https://stackoverflow.com/a/34245657))

You should change the `command` keyword in your `docker-compose.yml` to `entrypoint`.

```yaml
nitterproxy:
    container_name: nitterproxy
    image: nitterproxy
    ports:
      - 8080
    restart: always
    build:
      context: ./nitterproxy
    entrypoint: ["/nitter-rss-proxy", "-instances", "https://nitter.it/,https://nitter.ca/"]
```
